# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9e6725e7cf06913d2b73886add2c3ec533fd8032987e336667952fa3377ed30e7a47268cdc99db2c3c3d6aba9c223160b2c1f606cd15f05e3a870632b3870e4f

test:
  secret_key_base: f9e7842738b06054cea497f32ab4ff344d3ac670f15aca7ffa7a50d42267de68fee585d6f983a5ef8b14a29989e8131f1c06a9a6b57b454b49475cf24a2234a4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
